{
  "name": "SemanticModel",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-AU",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "DateTable",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "year",
            "dataType": "int64",
            "formatString": "0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month_name",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "month_year",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "quarter",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "financial_year",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "is_first_of_month",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTable",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "ADDCOLUMNS(",
                "    CALENDAR(DATE(1978,1,1), TODAY()),",
                "    \"year\",             YEAR([Date]),",
                "    \"month_number\",     MONTH([Date]),",
                "    \"month_name\",       FORMAT([Date], \"MMM\"),",
                "    \"month_year\",       FORMAT([Date], \"MMM yyyy\"),",
                "    \"quarter\",          \"Q\" & FORMAT([Date], \"Q\"),",
                "    \"financial_year\",   IF(MONTH([Date])>=7,",
                "                          \"FY\"&TEXT(YEAR([Date])+1,\"0\"),",
                "                          \"FY\"&TEXT(YEAR([Date]),\"0\")),",
                "    \"is_first_of_month\",IF(DAY([Date])=1, 1, 0)",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"DateTable\",\"ColumnName\":\"Date\"},\"LinkType\":\"GlobalCalendar\"}]"
          }
        ]
      },
      {
        "name": "NationalOverview",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "unemployed_thousands",
            "dataType": "double",
            "sourceColumn": "unemployed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "unemployment_rate_pct",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "participation_rate_pct",
            "dataType": "double",
            "sourceColumn": "participation_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "emp_to_pop_ratio_pct",
            "dataType": "double",
            "sourceColumn": "emp_to_pop_ratio_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "unemployment_rate_mom_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_mom_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_mom_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_mom_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "unemployment_rate_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"<your-server>.database.windows.net\", \"<your-database>\", [Query = \"SELECT * FROM mart.v_national_overview ORDER BY date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"employed_thousands\", type number}, {\"unemployed_thousands\", type number}, {\"unemployment_rate_pct\", type number}, {\"participation_rate_pct\", type number}, {\"emp_to_pop_ratio_pct\", type number}, {\"unemployment_rate_mom_change_ppt\", type number}, {\"employed_mom_change_pct\", type number}, {\"unemployment_rate_yoy_change_ppt\", type number}, {\"employed_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ]
      },
      {
        "name": "UnemploymentByState",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "region_code",
            "dataType": "string",
            "sourceColumn": "region_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "region_name",
            "dataType": "string",
            "sourceColumn": "region_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "unemployment_rate_pct",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "unemployment_rate_mom_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_mom_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "unemployment_rate_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"<your-server>.database.windows.net\", \"<your-database>\", [Query = \"SELECT * FROM mart.v_unemployment_by_state ORDER BY region_name, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"region_code\", type text}, {\"region_name\", type text}, {\"employed_thousands\", type number}, {\"unemployment_rate_pct\", type number}, {\"unemployment_rate_mom_change_ppt\", type number}, {\"unemployment_rate_yoy_change_ppt\", type number}, {\"employed_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ]
      },
      {
        "name": "IndustryBreakdown",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "industry_code",
            "dataType": "string",
            "sourceColumn": "industry_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "industry_name",
            "dataType": "string",
            "sourceColumn": "industry_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_yoy_change_thousands",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "rank_by_employment",
            "dataType": "int64",
            "sourceColumn": "rank_by_employment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "growth_category",
            "dataType": "string",
            "sourceColumn": "growth_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "is_focus_industry",
            "dataType": "int64",
            "sourceColumn": "is_focus_industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "is_latest_year",
            "dataType": "int64",
            "sourceColumn": "is_latest_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"<your-server>.database.windows.net\", \"<your-database>\", [Query = \"SELECT * FROM mart.v_industry_breakdown ORDER BY industry_name, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"industry_code\", type text}, {\"industry_name\", type text}, {\"employed_thousands\", type number}, {\"employed_yoy_change_thousands\", type number}, {\"employed_yoy_change_pct\", type number}, {\"rank_by_employment\", Int64.Type}, {\"growth_category\", type text}, {\"is_focus_industry\", Int64.Type}, {\"is_latest_year\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ]
      },
      {
        "name": "FulltimeParttime",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "sex_code",
            "dataType": "string",
            "sourceColumn": "sex_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "sex_label",
            "dataType": "string",
            "sourceColumn": "sex_label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "employed_fulltime_thousands",
            "dataType": "double",
            "sourceColumn": "employed_fulltime_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_parttime_thousands",
            "dataType": "double",
            "sourceColumn": "employed_parttime_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_total_thousands",
            "dataType": "double",
            "sourceColumn": "employed_total_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "fulltime_share_pct",
            "dataType": "double",
            "sourceColumn": "fulltime_share_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "parttime_share_pct",
            "dataType": "double",
            "sourceColumn": "parttime_share_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "fulltime_share_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "fulltime_share_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_total_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_total_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"<your-server>.database.windows.net\", \"<your-database>\", [Query = \"SELECT * FROM mart.v_fulltime_parttime ORDER BY sex_label, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"sex_code\", type text}, {\"sex_label\", type text}, {\"employed_fulltime_thousands\", type number}, {\"employed_parttime_thousands\", type number}, {\"employed_total_thousands\", type number}, {\"fulltime_share_pct\", type number}, {\"parttime_share_pct\", type number}, {\"fulltime_share_yoy_change_ppt\", type number}, {\"employed_total_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "isHidden": true,
        "columns": [
          {
            "name": "Placeholder",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Latest Unemployment Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest Employed Thousands",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[employed_thousands]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "#,0.0"
          },
          {
            "name": "Latest Participation Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[participation_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest Emp To Pop Ratio",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[emp_to_pop_ratio_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Unemployment Rate MoM Change",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_mom_change_ppt]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "Employed YoY Change Pct",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[employed_yoy_change_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "Unemployment Rate Subtitle",
            "expression": "VAR Ch=[Unemployment Rate MoM Change] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\" ppt vs last month\"",
            "displayFolder": "Overview KPIs"
          },
          {
            "name": "Employed Subtitle",
            "expression": "VAR Ch=[Employed YoY Change Pct] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\"% vs last year\"",
            "displayFolder": "Overview KPIs"
          },
          {
            "name": "National Avg Unemployment Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "State KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest Industry Employed",
            "expression": "CALCULATE(MAX(IndustryBreakdown[employed_thousands]),IndustryBreakdown[is_latest_year]=1)",
            "displayFolder": "Industry KPIs",
            "formatString": "#,0.0"
          },
          {
            "name": "Latest Industry YoY Change",
            "expression": "CALCULATE(MAX(IndustryBreakdown[employed_yoy_change_pct]),IndustryBreakdown[is_latest_year]=1)",
            "displayFolder": "Industry KPIs",
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "Latest FT Share Persons",
            "expression": "CALCULATE(MAX(FulltimeParttime[fulltime_share_pct]),FulltimeParttime[is_latest_month]=1,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest PT Share Persons",
            "expression": "CALCULATE(MAX(FulltimeParttime[parttime_share_pct]),FulltimeParttime[is_latest_month]=1,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "0.00"
          },
          {
            "name": "FT Share YoY Change",
            "expression": "VAR D=MAX(FulltimeParttime[date]) RETURN CALCULATE(MAX(FulltimeParttime[fulltime_share_yoy_change_ppt]),FulltimeParttime[date]=D,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "FT Share Subtitle",
            "expression": "VAR Ch=[FT Share YoY Change] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\" ppt vs last year\"",
            "displayFolder": "FT PT KPIs"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows({}, type table [Placeholder = Int64.Type])",
                "in",
                "    Source"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "afe57fb7-f9a8-414c-9d5b-e9ce2ec986b7",
        "fromTable": "NationalOverview",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "e3782930-10fa-4f71-94cd-f1e977bfd393",
        "fromTable": "UnemploymentByState",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "374f056c-a27b-4e7b-9a34-9f957484368f",
        "fromTable": "FulltimeParttime",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "803c70a4-6701-4525-97e9-caedd0dedf41",
        "fromTable": "IndustryBreakdown",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DateTable\",\"NationalOverview\",\"UnemploymentByState\",\"IndustryBreakdown\",\"FulltimeParttime\",\"_Measures\"]"
      }
    ]
  }
}