{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-AU",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "DateTable",
        "description": "Contiguous daily date dimension (1978→today) for time intelligence; marked as the model date table.",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "Date"
          },
          {
            "name": "year",
            "dataType": "int64",
            "formatString": "0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "year"
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "month_number"
          },
          {
            "name": "month_name",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "month_name"
          },
          {
            "name": "month_year",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "month_year"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "quarter"
          },
          {
            "name": "financial_year",
            "dataType": "string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "financial_year"
          },
          {
            "name": "is_first_of_month",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sourceColumn": "is_first_of_month"
          }
        ],
        "partitions": [
          {
            "name": "DateTable",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Start = #date(1978, 1, 1),",
                "    End = Date.From(DateTime.LocalNow()),",
                "    Dates = List.Dates(Start, Duration.Days(End - Start) + 1, #duration(1, 0, 0, 0)),",
                "    Source = Table.FromList(Dates, Splitter.SplitByNothing(), {\"Date\"}),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"Date\", type date}}),",
                "    A1 = Table.AddColumn(Typed, \"year\", each Date.Year([Date]), Int64.Type),",
                "    A2 = Table.AddColumn(A1, \"month_number\", each Date.Month([Date]), Int64.Type),",
                "    A3 = Table.AddColumn(A2, \"month_name\", each Date.ToText([Date], [Format=\"MMM\", Culture=\"en-AU\"]), type text),",
                "    A4 = Table.AddColumn(A3, \"month_year\", each Date.ToText([Date], [Format=\"MMM yyyy\", Culture=\"en-AU\"]), type text),",
                "    A5 = Table.AddColumn(A4, \"quarter\", each \"Q\" & Text.From(Date.QuarterOfYear([Date])), type text),",
                "    A6 = Table.AddColumn(A5, \"financial_year\", each if Date.Month([Date]) >= 7 then \"FY\" & Text.From(Date.Year([Date]) + 1) else \"FY\" & Text.From(Date.Year([Date])), type text),",
                "    A7 = Table.AddColumn(A6, \"is_first_of_month\", each if Date.Day([Date]) = 1 then 1 else 0, Int64.Type)",
                "in",
                "    A7"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"DateTable\",\"ColumnName\":\"Date\"},\"LinkType\":\"GlobalCalendar\"}]"
          }
        ]
      },
      {
        "name": "NationalOverview",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "unemployed_thousands",
            "dataType": "double",
            "sourceColumn": "unemployed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "unemployment_rate_pct",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "participation_rate_pct",
            "dataType": "double",
            "sourceColumn": "participation_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "emp_to_pop_ratio_pct",
            "dataType": "double",
            "sourceColumn": "emp_to_pop_ratio_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "unemployment_rate_mom_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_mom_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_mom_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_mom_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "unemployment_rate_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"melvind.database.windows.net\", \"aus_job_dashboard\", [Query = \"SELECT * FROM mart.v_national_overview ORDER BY date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"employed_thousands\", type number}, {\"unemployed_thousands\", type number}, {\"unemployment_rate_pct\", type number}, {\"participation_rate_pct\", type number}, {\"emp_to_pop_ratio_pct\", type number}, {\"unemployment_rate_mom_change_ppt\", type number}, {\"employed_mom_change_pct\", type number}, {\"unemployment_rate_yoy_change_ppt\", type number}, {\"employed_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ],
        "description": "National monthly labour-force headline series (seasonally adjusted): employment, unemployment rate, participation rate and MoM/YoY changes."
      },
      {
        "name": "UnemploymentByState",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "region_code",
            "dataType": "string",
            "sourceColumn": "region_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "region_name",
            "dataType": "string",
            "sourceColumn": "region_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "description": "State or territory name.",
            "dataCategory": "StateOrProvince"
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0",
            "description": "Employed persons in thousands, seasonally adjusted."
          },
          {
            "name": "unemployment_rate_pct",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00",
            "description": "Unemployment rate (%), seasonally adjusted."
          },
          {
            "name": "unemployment_rate_mom_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_mom_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "unemployment_rate_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "unemployment_rate_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"melvind.database.windows.net\", \"aus_job_dashboard\", [Query = \"SELECT * FROM mart.v_unemployment_by_state ORDER BY region_name, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"region_code\", type text}, {\"region_name\", type text}, {\"employed_thousands\", type number}, {\"unemployment_rate_pct\", type number}, {\"unemployment_rate_mom_change_ppt\", type number}, {\"unemployment_rate_yoy_change_ppt\", type number}, {\"employed_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ],
        "description": "Monthly unemployment rate and employment by state/territory."
      },
      {
        "name": "IndustryBreakdown",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "industry_code",
            "dataType": "string",
            "sourceColumn": "industry_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "industry_name",
            "dataType": "string",
            "sourceColumn": "industry_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "description": "ANZSIC industry division name."
          },
          {
            "name": "employed_thousands",
            "dataType": "double",
            "sourceColumn": "employed_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0",
            "description": "Employed persons in thousands."
          },
          {
            "name": "employed_yoy_change_thousands",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00",
            "description": "Year-on-year change in employed persons (%)."
          },
          {
            "name": "rank_by_employment",
            "dataType": "int64",
            "sourceColumn": "rank_by_employment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "growth_category",
            "dataType": "string",
            "sourceColumn": "growth_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "description": "Growing / shrinking classification based on YoY change."
          },
          {
            "name": "is_focus_industry",
            "dataType": "int64",
            "sourceColumn": "is_focus_industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "is_latest_year",
            "dataType": "int64",
            "sourceColumn": "is_latest_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"melvind.database.windows.net\", \"aus_job_dashboard\", [Query = \"SELECT * FROM mart.v_industry_breakdown ORDER BY industry_name, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"industry_code\", type text}, {\"industry_name\", type text}, {\"employed_thousands\", type number}, {\"employed_yoy_change_thousands\", type number}, {\"employed_yoy_change_pct\", type number}, {\"rank_by_employment\", Int64.Type}, {\"growth_category\", type text}, {\"is_focus_industry\", Int64.Type}, {\"is_latest_year\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ],
        "description": "Employed persons by ANZSIC industry division with year-on-year growth and growing/shrinking category."
      },
      {
        "name": "FulltimeParttime",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "Short Date"
          },
          {
            "name": "sex_code",
            "dataType": "string",
            "sourceColumn": "sex_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "sex_label",
            "dataType": "string",
            "sourceColumn": "sex_label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "description": "Persons, Male or Female. Persons = Male + Female, so filter to one to avoid double-counting in totals."
          },
          {
            "name": "employed_fulltime_thousands",
            "dataType": "double",
            "sourceColumn": "employed_fulltime_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_parttime_thousands",
            "dataType": "double",
            "sourceColumn": "employed_parttime_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "employed_total_thousands",
            "dataType": "double",
            "sourceColumn": "employed_total_thousands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "fulltime_share_pct",
            "dataType": "double",
            "sourceColumn": "fulltime_share_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "parttime_share_pct",
            "dataType": "double",
            "sourceColumn": "parttime_share_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "fulltime_share_yoy_change_ppt",
            "dataType": "double",
            "sourceColumn": "fulltime_share_yoy_change_ppt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "employed_total_yoy_change_pct",
            "dataType": "double",
            "sourceColumn": "employed_total_yoy_change_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "is_latest_month",
            "dataType": "int64",
            "sourceColumn": "is_latest_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"melvind.database.windows.net\", \"aus_job_dashboard\", [Query = \"SELECT * FROM mart.v_fulltime_parttime ORDER BY sex_label, date\"]),",
                "    #\"T\" = Table.TransformColumnTypes(Source, {{\"date\", type date}, {\"sex_code\", type text}, {\"sex_label\", type text}, {\"employed_fulltime_thousands\", type number}, {\"employed_parttime_thousands\", type number}, {\"employed_total_thousands\", type number}, {\"fulltime_share_pct\", type number}, {\"parttime_share_pct\", type number}, {\"fulltime_share_yoy_change_ppt\", type number}, {\"employed_total_yoy_change_pct\", type number}, {\"is_latest_month\", Int64.Type}})",
                "in",
                "    #\"T\""
              ]
            }
          }
        ],
        "description": "Full-time vs part-time employment split by sex (Persons = Male + Female)."
      },
      {
        "name": "_Measures",
        "isHidden": true,
        "columns": [
          {
            "name": "Placeholder",
            "dataType": "int64",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Latest Unemployment Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest Employed Thousands",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[employed_thousands]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "#,0.0"
          },
          {
            "name": "Latest Participation Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[participation_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Latest Emp To Pop Ratio",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[emp_to_pop_ratio_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "0.00"
          },
          {
            "name": "Unemployment Rate MoM Change",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_mom_change_ppt]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "Employed YoY Change Pct",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[employed_yoy_change_pct]),NationalOverview[date]=D)",
            "displayFolder": "Overview KPIs",
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "Unemployment Rate Subtitle",
            "expression": "VAR Ch=[Unemployment Rate MoM Change] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\" ppt vs last month\"",
            "displayFolder": "Overview KPIs",
            "description": "Arrow + month-on-month change in percentage points, for the KPI card subtitle."
          },
          {
            "name": "Employed Subtitle",
            "expression": "VAR Ch=[Employed YoY Change Pct] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\"% vs last year\"",
            "displayFolder": "Overview KPIs",
            "description": "Arrow + year-on-year employment change (%), for the KPI card subtitle."
          },
          {
            "name": "National Avg Unemployment Rate",
            "expression": "VAR D=MAX(NationalOverview[date]) RETURN CALCULATE(MAX(NationalOverview[unemployment_rate_pct]),NationalOverview[date]=D)",
            "displayFolder": "State KPIs",
            "formatString": "0.00",
            "description": "National unemployment rate at the latest month (reference line for the state view)."
          },
          {
            "name": "Latest Industry Employed",
            "expression": "CALCULATE(MAX(IndustryBreakdown[employed_thousands]),IndustryBreakdown[is_latest_year]=1)",
            "displayFolder": "Industry KPIs",
            "formatString": "#,0.0"
          },
          {
            "name": "Latest Industry YoY Change",
            "expression": "CALCULATE(MAX(IndustryBreakdown[employed_yoy_change_pct]),IndustryBreakdown[is_latest_year]=1)",
            "displayFolder": "Industry KPIs",
            "formatString": "+0.00;-0.00"
          },
          {
            "name": "Latest FT Share Persons",
            "expression": "CALCULATE(MAX(FulltimeParttime[fulltime_share_pct]),FulltimeParttime[is_latest_month]=1,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "0.00",
            "description": "Full-time share of employment (%) for Persons at the latest month."
          },
          {
            "name": "Latest PT Share Persons",
            "expression": "CALCULATE(MAX(FulltimeParttime[parttime_share_pct]),FulltimeParttime[is_latest_month]=1,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "0.00",
            "description": "Part-time share of employment (%) for Persons at the latest month."
          },
          {
            "name": "FT Share YoY Change",
            "expression": "VAR D=MAX(FulltimeParttime[date]) RETURN CALCULATE(MAX(FulltimeParttime[fulltime_share_yoy_change_ppt]),FulltimeParttime[date]=D,FulltimeParttime[sex_label]=\"Persons\")",
            "displayFolder": "FT PT KPIs",
            "formatString": "+0.000;-0.000"
          },
          {
            "name": "FT Share Subtitle",
            "expression": "VAR Ch=[FT Share YoY Change] VAR Ar=IF(Ch>0,\"▲\",IF(Ch<0,\"▼\",\"–\")) RETURN Ar&\" \"&FORMAT(ABS(Ch),\"0.0\")&\" ppt vs last year\"",
            "displayFolder": "FT PT KPIs"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows({}, type table [Placeholder = Int64.Type])",
                "in",
                "    Source"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6ab01af0-9824-447f-865f-3c3a97ba2cf2",
        "fromTable": "NationalOverview",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "7a4c8785-bb84-464c-88ee-303fa09ed721",
        "fromTable": "UnemploymentByState",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "dc943b9d-ab4e-4c6b-a654-0188cfb1ffbe",
        "fromTable": "FulltimeParttime",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "47ec6957-f262-4218-908a-0a1f462701ab",
        "fromTable": "IndustryBreakdown",
        "fromColumn": "date",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DateTable\",\"NationalOverview\",\"UnemploymentByState\",\"IndustryBreakdown\",\"FulltimeParttime\",\"_Measures\"]"
      }
    ]
  }
}