"""
check_mart_contract.py — Assert the mart still matches what the report expects.

dbt tests police the data. Nothing polices the seam between the warehouse and
the two things that read it, and that seam is quiet when it breaks: Power Query
binds columns by NAME, so renaming, dropping or reordering a mart column leaves
dbt perfectly green while the Power BI model and the Excel workbook fail on
their next refresh — or worse, load with a column silently missing.

That is not hypothetical. Rebinding the report during the v1 -> v2 migration
turned up `is_latest_year` and `is_focus_industry` declared in the opposite
order from the view that supplies them. Harmless, because Power Query binds by
name — but nothing would have told us if it had been a rename.

So this compares, for each table in the generated `model.bim`:

    the columns the semantic model declares   vs   the columns the view returns

and fails on any difference. `model.bim` is generated by build_report.py, so
changing a mart column and regenerating the report passes; changing the mart
alone does not.

Run: py -3 scripts/check_mart_contract.py
"""

import json
import re
import sys
from pathlib import Path

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

ROOT = Path(__file__).resolve().parent.parent
MODEL_BIM = ROOT / "powerbi" / "aus_job_dashboard.SemanticModel" / "model.bim"
EXPORT_DIR = ROOT / "excel" / "data"

sys.path.insert(0, str(ROOT / "scripts"))
from load_raw import build_conn_str  # noqa: E402


def model_bindings() -> list[tuple[str, str, list[str]]]:
    """(table name, mart view, declared columns) for every SQL-backed model table."""
    bim = json.loads(MODEL_BIM.read_text(encoding="utf-8"))
    out = []
    for table in bim["model"]["tables"]:
        partitions = table.get("partitions") or []
        if not partitions:
            continue
        expression = partitions[0].get("source", {}).get("expression")
        if not isinstance(expression, list):
            continue
        m = re.search(r"FROM\s+(mart\.\w+)", "\n".join(expression))
        if not m:
            continue
        out.append((table["name"], m.group(1), [c["name"] for c in table["columns"]]))
    return out


def main() -> None:
    if not MODEL_BIM.exists():
        sys.exit(f"ERROR: {MODEL_BIM} not found — run: py -3 powerbi/build_report.py")

    engine = create_engine(f"mssql+pyodbc:///?odbc_connect={build_conn_str()}")
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except SQLAlchemyError as e:
        print(f"ERROR: could not connect to the warehouse.\n{e}\n")
        print("Is it running?  docker compose up -d")
        sys.exit(1)

    bindings = model_bindings()
    if not bindings:
        sys.exit("ERROR: model.bim declares no mart-backed tables — that cannot be right.")

    print("=== Mart contract ===\n")
    failures = []

    for table, view, declared in bindings:
        try:
            actual = list(pd.read_sql(f"SELECT TOP 0 * FROM {view}", engine).columns)
        except SQLAlchemyError:
            failures.append(f"{table}: view {view} does not exist or is not readable")
            print(f"  {table:<22} {view:<32} MISSING VIEW")
            continue

        if declared == actual:
            print(f"  {table:<22} {view:<32} ok ({len(actual)} columns)")
            continue

        missing = [c for c in declared if c not in actual]
        added = [c for c in actual if c not in declared]
        if missing or added:
            detail = []
            if missing:
                detail.append(f"declared but not in the view: {missing}")
            if added:
                detail.append(f"in the view but not declared: {added}")
            failures.append(f"{table} / {view}: " + "; ".join(detail))
            print(f"  {table:<22} {view:<32} MISMATCH")
        else:
            failures.append(
                f"{table} / {view}: same columns, different order\n"
                f"      model: {declared}\n"
                f"      view : {actual}"
            )
            print(f"  {table:<22} {view:<32} ORDER DIFFERS")

    # The workbook reads the exported CSVs, so their headers are the other half
    # of the same contract. Skipped when the export has not been run.
    if EXPORT_DIR.exists():
        print("\n=== Excel export headers ===\n")
        view_for = {
            "national_overview": "mart.v_national_overview",
            "unemployment_by_state": "mart.v_unemployment_by_state",
            "fulltime_parttime": "mart.v_fulltime_parttime",
            "industry_breakdown": "mart.v_industry_breakdown",
        }
        for stem, view in view_for.items():
            path = EXPORT_DIR / f"{stem}.csv"
            if not path.exists():
                print(f"  {stem:<24} not exported yet — skipped")
                continue
            header = path.read_text(encoding="utf-8-sig").splitlines()[0].split(",")
            actual = list(pd.read_sql(f"SELECT TOP 0 * FROM {view}", engine).columns)
            if header == actual:
                print(f"  {stem:<24} ok ({len(header)} columns)")
            else:
                failures.append(
                    f"excel/data/{stem}.csv header does not match {view} — "
                    "re-run: py -3 scripts/export_mart.py"
                )
                print(f"  {stem:<24} STALE")

    if failures:
        print("\nCONTRACT VIOLATIONS:\n")
        for f in failures:
            print(f"  - {f}")
        print("\nThe Power BI model and the Excel workbook bind these columns by name.")
        print("Fix the mart model, or update powerbi/build_report.py and regenerate.")
        sys.exit(1)

    print("\n=== Contract intact ===")


if __name__ == "__main__":
    main()
